"""empty message

Revision ID: 927aa5f2a67e
Revises: 44648ec72310
Create Date: 2020-04-21 15:08:18.633672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927aa5f2a67e'
down_revision = '44648ec72310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'completed')
    # ### end Alembic commands ###
